Fix b&t venv=None (#4758)
Fix regression (potentially from
https://github.com/qcom-ai-hub/ai-hub-models-internal/pull/4713 ?) that
caused `build_and_test.py --venv=none` to fail with:
```
  File "/local/mnt/workspace/kory/Developer/ai-hub-models-internal/scripts/build_and_test.py", line 239, in create_venv
    false_task=CreateVenvTask(self.venv_path, self.python_executable),
  File "/local/mnt/workspace/kory/Developer/ai-hub-models-internal/scripts/tasks/venv.py", line 122, in __init__
    f'"--venv={Path(venv_path).as_posix()}" --no-sync',
  File "/kory/miniconda3/envs/QAIHM/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/kory/miniconda3/envs/QAIHM/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/kory/miniconda3/envs/QAIHM/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

`--venv=none` is used when you want to use your currently active
environment instead of a specific venv.